apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: desched-dynthresholds
  name: desched-dynthresholds
  namespace: openshift-kube-descheduler-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desched-dynthresholds
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: desched-dynthresholds
    spec:
      serviceAccountName: openshift-descheduler
      containers:
      - image: quay.io/fedora/fedora:latest
        name: fedora
        resources: {}
        command: ["/usr/bin/bash"]
        args: ["/app/desched-dynthresholds.sh"]
        volumeMounts:
        - name: "script"
          mountPath: "/app"
      restartPolicy: Always
      terminationGracePeriod: 0
      volumes:
      # kubectl create configmap desched-dynthresholds --from-file desched-dynthresholds.sh
        - name: "script"
          configMap:
            name: "desched-dynthresholds"
status: {}
